### ISSUE TITLE
Could not download binary

### ISSUE THREAD

**Issue by foxhound87** [zeit/now-app#102]
ReferenceError: await is not defined
    at /Users/cla/Apps/Dev/Now.app/Contents/Resources/app/dist/main.js:2571:17
    at next (<anonymous>)
    at step (/Users/cla/Apps/Dev/Now.app/Contents/Resources/app/dist/main.js:2496:192)
    at /Users/cla/Apps/Dev/Now.app/Contents/Resources/app/dist/main.js:2496:438
    at /Users/cla/Apps/Dev/Now.app/Contents/Resources/app/dist/main.js:2496:100
    at RetryOperation._fn (/Users/cla/Apps/Dev/Now.app/Contents/Resources/app/node_modules/async-retry/build/lib/index.js:44:15)
    at Timeout._onTimeout (/Users/cla/Apps/Dev/Now.app/Contents/Resources/app/node_modules/retry/lib/retry_operation.js:59:10)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)

**Comment by leo** [comment]
Found the bug! Fixing... 😊

**Comment by leo** [comment]
Should be fixed now! https://github.com/zeit/now-app/releases/tag/0.2.6
