### ISSUE TITLE
Could not download binary

### ISSUE THREAD

**Issue by Joham** [zeit/now-app#107]
ReferenceError: await is not defined
    at /Users/Medialift/Downloads/Now.app/Contents/Resources/app/dist/main.js:2571:17
    at next (<anonymous>)
    at step (/Users/Medialift/Downloads/Now.app/Contents/Resources/app/dist/main.js:2496:192)
    at /Users/Medialift/Downloads/Now.app/Contents/Resources/app/dist/main.js:2496:438
    at /Users/Medialift/Downloads/Now.app/Contents/Resources/app/dist/main.js:2496:100
    at RetryOperation._fn (/Users/Medialift/Downloads/Now.app/Contents/Resources/app/node_modules/async-retry/build/lib/index.js:44:15)
    at Timeout._onTimeout (/Users/Medialift/Downloads/Now.app/Contents/Resources/app/node_modules/retry/lib/retry_operation.js:59:10)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)

**Comment by leo** [comment]
Fixed in https://github.com/zeit/now-app/releases/tag/0.2.6 😊
