### ISSUE TITLE
Unhandled error appeared

### ISSUE THREAD

**Issue by TooTallNate** [zeit/now-app#129]
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: react.js:195:20.
    at BrowserWindow.callIntoRenderer (/Applications/Now.app/Contents/Resources/electron.asar/browser/rpc-server.js:190:19)
    at emitOne (events.js:101:20)
    at BrowserWindow.emit (events.js:188:7)

**Comment by TooTallNate** [comment]
I was on Now.app v0.1.1 (for some reason it was saying that was up-to-date. Had to download manually from zeit.co to get v0.3.1 😐)

**Comment by leo** [comment]
Hehe... These old versions don't support auto updates. I've introduced them around 0.2.3 or something... 😊
