### ISSUE TITLE
Now-app fails to download now when behind a corporate firewall.

### ISSUE THREAD

**Issue by teehemkay** [zeit/now-app#163]
Setup: Mac OS X Yosemite 10.10.5

When I try to install now-app, the installation get stuck in the "Downloading..." phase.
I suspect this is because my Mac is behind a corporate firewall.

Here's the log

```
[2016-10-26 10:40:07:0250] [info] FetchError: request to https://api.github.com/repos/zeit/now/releases/latest failed, reason: getaddrinfo ENOTFOUND api.github.com api.github.com:443
    at ClientRequest.<anonymous> (/Applications/Now.app/Contents/Resources/app/node_modules/node-fetch/index.js:127:11)
[2016-10-26 11:04:47:0108] [info] FetchError: request to https://api.github.com/repos/zeit/now/releases/latest failed, reason: getaddrinfo ENOTFOUND api.github.com api.github.com:443
    at ClientRequest.<anonymous> (/Applications/Now.app/Contents/Resources/app/node_modules/node-fetch/index.js:127:11)
[2016-10-31 16:37:14:0865] [info] FetchError: request to https://api.github.com/repos/zeit/now/releases/latest failed, reason: getaddrinfo ENOTFOUND api.github.com api.github.com:443
    at ClientRequest.<anonymous> (/Applications/Now.app/Contents/Resources/app/node_modules/node-fetch/index.js:127:11)
[2016-10-31 17:08:59:0559] [info] FetchError: request to https://api.github.com/repos/zeit/now/releases/latest failed, reason: getaddrinfo ENOTFOUND api.github.com api.github.com:443
    at ClientRequest.<anonymous> (/Applications/Now.app/Contents/Resources/app/node_modules/node-fetch/index.js:127:11)
    at Timeout.checkForUpdates [as _repeat] (/Applications/Now.app/Contents/Resources/app/dist/main.js:2597:28)
    at Timeout.checkForUpdates [as _repeat] (/Applications/Now.app/Contents/Resources/app/dist/main.js:2597:28)
    at Timeout.checkForUpdates [as _repeat] (/Applications/Now.app/Contents/Resources/app/dist/main.js:2597:28)
    at Timeout.checkForUpdates [as _repeat] (/Applications/Now.app/Contents/Resources/app/dist/main.js:2597:28)
```

**Comment by leo** [comment]
Will be solved with https://github.com/zeit/now-app/issues/177
