### ISSUE TITLE
Unhandled error appeared after automatic update

### ISSUE THREAD

**Issue by BurntCaramel** [zeit/now-app#176]
Error: write after end
    at writeAfterEnd (_stream_writable.js:166:12)
    at PassThrough.Writable.write (_stream_writable.js:217:5)
    at IncomingMessage.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at IncomingMessage.emit (events.js:188:7)
    at IncomingMessage.Readable.read (_stream_readable.js:381:10)
    at flow (_stream_readable.js:761:34)
    at resume_ (_stream_readable.js:743:3)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by leo** [comment]
Can be solved with https://github.com/zeit/now-app/issues/177
