### ISSUE TITLE
Unhandled error appeared

### ISSUE THREAD

**Issue by sunilshenoy** [zeit/now-app#200]
Error: write after end
    at writeAfterEnd (_stream_writable.js:166:12)
    at PassThrough.Writable.write (_stream_writable.js:217:5)
    at IncomingMessage.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at IncomingMessage.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at IncomingMessage.Readable.push (_stream_readable.js:134:10)
    at HTTPParser.parserOnBody (_http_common.js:129:22)
    at TLSSocket.socketOnData (_http_client.js:361:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:543:20)

**Comment by leo** [comment]
Will be fixed soon!
