### ISSUE TITLE
Unhandled error appeared

### ISSUE THREAD

**Issue by arakawarx7** [zeit/now-app#201]
Error: Object has been destroyed
    at Error (native)
    at exports.default (/Applications/Now.app/Contents/Resources/app/dist/main.js:2420:27)
    at Tray.toggleActivity (/Applications/Now.app/Contents/Resources/app/dist/main.js:497:35)
    at emitTwo (events.js:106:13)
    at Tray.emit (events.js:191:7)

**Comment by leo** [comment]
Will be fixed soon!
